version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI.CoworkingSpace/Dockerfile
    ports:
      - "5000:80"  # Hoặc port bạn dùng trong WebAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySqlConnectionStr=Server=mysql;Database=CoworkingSpace;User=trung;Password=trung220703;
    depends_on:
      redis:
        condition: service_healthy  # Chờ Redis sẵn sàng
      mysql:
        condition: service_started  # Chờ MySQL khởi động
    networks:
      - coworking-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: CoworkingSpace
      MYSQL_USER: trung
      MYSQL_PASSWORD: trung220703
    ports:
      - "3307:3306"
    networks:
      - coworking-network

  redis:
    image: redis:latest
    container_name: coworking-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # Kiểm tra Redis có phản hồi không
      interval: 5s                        # Kiểm tra mỗi 5 giây
      timeout: 3s                         # Timeout sau 3 giây
      retries: 5                          # Thử lại 5 lần trước khi coi là lỗi
    networks:
      - coworking-network
        
networks:
  coworking-network:
    driver: bridge
